### ISSUE TITLE
 logging in as admin without a username crashes the server

### ISSUE THREAD

**Issue by gunawan092w** [computernewb/collabvm-1.2.ts#9] opened 2024-02-06 17:21 UTC
Hi, yesterday i wrote my own collabvm bot in node.js.
Today, i added the function to make the bot log in as admin at every startup
but when i ran the bot, collabvm server crashed with this error message:

```
/path/to/collabvm-1.2.ts/build/guacutils.js:28
          command += current.toString().length + '.' + current;

TypeError: Cannot read properties from undefined (reading 'toString')
```

How i did was to send a websocket message, which is `5.admin,1,2,18.password`.
So what is going on, does that websocket message only works in client? (or cvm-webapp)

**Comment by gunawan092w** [comment] 2024-02-06 17:52
sorry i made a typo in the websocket message

`2.admin,1,2,18.password`

**Comment by elijahr2411** [comment] 2024-02-06 19:43
I'm unable to reproduce this crash with either of the messages you sent. Have you modified CollabVM server at all? Are you running the latest version?

Additionally, both of those messages are invalid syntax. The correct syntax is described [here](https://guacamole.apache.org/doc/0.9.5/gug/guacamole-protocol.html).

**Comment by gunawan092w** [comment] 2024-02-07 03:55
i'm running on latest collabvm server.
and i used this code to send message to the server so that the bot can log in as admin
```
const adminpass = '';
const modpass = '';

function client() {
  console.log(adminpass) // Just to identify whether password is confliting or not. Only temporary
  ws.on('connect', function(wsclient) {
    console.log('Bot connected!');
    
    const message = encodeCommand(['admin', '2', adminpass]);
    console.log(message) // Apperantly logs the encoded websocket message
    wsclient.sendUTF(message)
}

client();
```
![image](https://github.com/computernewb/collabvm-1.2.ts/assets/86261006/b91a814b-0b46-4aca-978e-01aa75e86752)

**Comment by gunawan092w** [comment] 2024-02-07 12:14
i rechecked with the guacamole documentation that you've attached there, and i see now that the syntax is incorrect.

So i went ahead and fixed it with this new one:
```
const loginadmin = "5.admin,1.2,4." + adminpass
wsclient.sendUTF(loginadmin,)
```
and it's still doesn't work.

![IMG_20240207_191414](https://github.com/computernewb/collabvm-1.2.ts/assets/86261006/c98b6519-4b4e-4345-ab61-4bed874992f5)
![IMG_20240207_191331](https://github.com/computernewb/collabvm-1.2.ts/assets/86261006/c7f089ab-9605-432e-b485-d83bcc915455)

**Comment by elijahr2411** [comment] 2024-02-07 15:34
I'm still not able to reproduce the server crash.

Would you mind sending the full source to your bot so I can investigate further?

**Comment by elijahr2411** [comment] 2024-02-07 15:53
Disregard that, we've found the issue.

The problem is that you're trying to log in as an admin before assigning a username, which crashes the VM

(this is a low-priority bug as it only works if you know the correct admin password)

The crash is fixed by 73ab61f, as any login attempts will now be ignored. To properly log in to the VM, you need to first send a 7.rename instruction.

**Comment by gunawan092w** [comment] 2024-02-07 16:41
a 7.rename instruction?
can you tell me the example of that?

**Comment by gunawan092w** [comment] 2024-02-07 17:08
sorry i'm kinda confused rn with the "7.rename" instruction thing
![image](https://github.com/computernewb/collabvm-1.2.ts/assets/86261006/c8fb6a0a-0570-4ec0-a9a5-205505c56200)

**Comment by gunawan092w** [comment] 2024-02-07 17:16
sorry just to make it clear, the bot did joined with assigned username

**Comment by gunawan092w** [comment] 2024-02-07 17:17
![image](https://github.com/computernewb/collabvm-1.2.ts/assets/86261006/d85931e0-41bf-4fc7-b935-954851464c62)
i just realized i have that code already

**Comment by coolgamer17223** [comment] 2024-02-07 17:26
we've tried to use 7.rename but the bot doesnt show up we used 6.rename instead and the bot showed up now we just arent able to login as admin

**Comment by MDMCK10** [comment] 2024-02-07 17:35
@coolgamer17223 @gunawan092w 

`6.rename` is correct, there was a typo in what @elijahr2411 sent.

However, instead of manually putting together the instructions, you should consider using something like this:

```js
function encode(string) {
	let command = '';

	for(var i = 0; i < string.length; i++) {
		let current = string[i];
		command += current.length + '.' + current;
		command += ( i < string.length - 1 ? ',' : ';');
	}
	return command;
}

// Example usage:
const changeuser = encode(['rename', config.name]);
```

This way, there is no need to manually specify the lengths.

**Comment by gunawan092w** [comment] 2024-02-07 17:43
we already have that in our code, but the problem is we can't still log in to admin

**Comment by coolgamer17223** [comment] 2024-02-07 17:43
We've already added the encoded functions. Also our bot's cant login to Admin.

**Comment by gunawan092w** [comment] 2024-02-07 17:44
do i attach my full cvm code so you guys can get into futher more investigation?

**Comment by elijahr2411** [comment] 2024-02-07 17:48
At this point the issue with the server has been solved, please create a discussion or a thread in our discord server to discuss problems with your code.

**Closed** 2024-02-07 17:48 UTC
